# Generated by Django 2.2.13 on 2020-10-26 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_historicalpermitactor_historicalpermitauthor_historicalpermitrequestactor_historicalpermitrequestval'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermitrequest',
            name='send_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'envoi"),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='send_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'envoi"),
        ),
        migrations.AlterField(
            model_name='historicalpermitrequest',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Rendre la demande publique'),
        ),
        migrations.AlterField(
            model_name='historicalpermitrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (4, 'Demande de compléments'), (3, 'En traitement'), (5, 'En validation'), (2, 'Approuvée'), (6, 'Refusée'), (7, 'Annonce réceptionnée')], default=0, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Rendre la demande publique'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (4, 'Demande de compléments'), (3, 'En traitement'), (5, 'En validation'), (2, 'Approuvée'), (6, 'Refusée'), (7, 'Annonce réceptionnée')], default=0, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='permitworkflowstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brouillon'), (1, 'Envoyée, en attente de traitement'), (4, 'Demande de compléments'), (3, 'En traitement'), (5, 'En validation'), (2, 'Approuvée'), (6, 'Refusée'), (7, 'Annonce réceptionnée')], verbose_name='statut'),
        ),
    ]
